project_id = "tshvbtrnlcigronrgxtx"

[functions.balasinaja]
verify_jwt = false

[functions.send-broadcast]
verify_jwt = true

[functions.process-scheduled-broadcasts]
verify_jwt = false

[functions.send-subscription-notification]
verify_jwt = false

[functions.send-welcome-notification]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.mayar-checkout]
verify_jwt = true

[functions.mayar-webhook]
verify_jwt = false

[functions.web-chat]
verify_jwt = false

[functions.embed-chat-proxy]
verify_jwt = false

[functions.mpwa-generate-qr]
verify_jwt = false